services:
  # -- DB 컨테이너 ----------------------------
  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  # -- Django(web) 컨테이너 --------------------
  web:
    build: .
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
    volumes:
      - static_data:/app/staticfiles
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy

  # -- Nginx(문지기) 컨테이너 -------------------
  nginx:
    build: ./nginx
    volumes:
      - static_data:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web

# -- named voluem 선언 -----------------------
volumes:
  postgres_data:
  static_data:
